# Generated by Django 4.2.27 on 2026-02-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_option',
            field=models.CharField(choices=[('pickup', 'Self Pickup'), ('delivery', 'Home Delivery')], default='pickup', max_length=10),
        ),
    ]
