# Generated by Django 4.2.27 on 2026-02-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_conversation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='return_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('upcoming', 'Upcoming'), ('pickup_requested', 'Pickup Requested')], default='upcoming', max_length=20),
        ),
    ]
