# Generated by Django 4.2.27 on 2026-02-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_usersettings_savedlocation_paymentmethod_kycdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
