# Generated by Django 4.2.27 on 2026-03-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_review_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
    ]
