# Generated by Django 4.2.27 on 2026-03-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_kyc_rejection_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdocument',
            name='address',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='email',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='features',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='images',
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='rentals.vehicle')),
            ],
        ),
    ]
