# Generated by Django 4.2.27 on 2026-03-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_remove_kycdocument_address_remove_kycdocument_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclefeature',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_set', to='rentals.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='rentals.vehicle'),
        ),
    ]
