# Generated by Django 4.2.27 on 2026-03-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0024_rentalshop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seating',
            field=models.IntegerField(blank=True, choices=[(5, '5 Seater'), (7, '7 Seater')], null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=10),
        ),
    ]
