# Generated by Django 4.2.27 on 2026-03-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffComplaint',
        ),
    ]
