# Generated by Django 6.0.2 on 2026-02-16 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('operating_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('images', models.JSONField(default=list)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('seating', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('features', models.JSONField(default=list)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='rentals.rentalshop')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rentals.rentalshop')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rentals.vehicle')),
            ],
        ),
    ]
